---
author: "Ivan Kostine, Charlène Khairallah, Niccolo Cherubini"
date: "2023-11-18"
output: html_document
---

```{r Import and clean names, include=FALSE}
# Create an empty list to store the data frames
commodity_data_list <- list()

# List of commodity sheet names
commodities <- c(
  "Cotton", "Cocoa", "Silver", "CrudeOil", "Sugar", "NagGas", "HeatOil",
  "Gasoline", "Corn", "Soybeans", "SoyOil", "SoyMeal", "Wheat", "Gold",
  "Platinum", "Palladium", "FedCattle", "LiveCattle", "LeanHogs","Copper", "Coffee"
)

# Load data for each commodity and store it in the list
for (commodity in commodities) {
  data <- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet = commodity) %>% rename(
    "Open_Interest" = "Open Interest",
    "Producer_Longs"="Producer/Merchant/Processor/User Longs",
    "Producer_Shorts"="Producer/Merchant/Processor/User Shorts",
    "Swap_Dealer_Longs"="Swap Dealer Longs",
    "Swap_Dealer_Shorts"="Swap Dealer Shorts",
    "Swap_Dealer_Spreads"="Swap Dealer Spreads",
    "Money_Manager_Longs"="Money Manager Longs",
    "Money_Manager_Shorts"="Money Manager Shorts",
    "Money_Manager_Spreads"="Money Manager Spreads",
    "Other_Reportable_Longs"="Other Reportable Longs",
    "Other_Reportable_Shorts"="Other Reportable Shorts",
    "Other_Reportable_Shorts"="Other Reportable Shorts",
    "Total_Reportable_Longs"="Total Reportable Longs",
    "Total_Reportable_Shorts"="Total Reportable Shorts",
    "Non_Reportable_Longs"="Non Reportable Longs",
    "Non_Reportable_Shorts"="Non Reportable Shorts") %>% as_tsibble(index = Date, regular = FALSE)
  commodity_data_list[[commodity]] <- data
}


```

```{r Mean of future prices}
Daily_futures_prices <- read_excel("data/DailyFuturePrices_2003_2023.xlsx", sheet="Original")

#Selecting the needed columns for the soft commodities and the crude oil
Daily_futures_prices <- Daily_futures_prices[, c(1:13, 53:55)]
Daily_futures_prices <- Daily_futures_prices[-c(1,2),]
colnames(Daily_futures_prices)[1] = "Date"

#Transforming types to numeric
Daily_futures_prices[, 2:16] <- lapply(2:16, function(x) as.numeric(Daily_futures_prices[[x]]))

#Taking the mean of the future prices
commo_mean <- function(set) {
  result_set <- set %>% 
    mutate(Date,
           Cotton = rowMeans(select(., as.numeric(2:4)), na.rm = TRUE),
           Coffee = rowMeans(select(., 5:7),na.rm = TRUE),
           Sugar = rowMeans(select(., 8:10),na.rm = TRUE),
           Cocoa = rowMeans(select(., 11:13), na.rm = TRUE),
           Oil = rowMeans(select(., 14:16), na.rm = TRUE),
           .keep = "none")
  
  return(result_set)
}

# Compute mean by group
Daily_prices_mean <- commo_mean(Daily_futures_prices)

#Creating a column for day of the week
Daily_prices_mean$Day <- weekdays(as.Date(Daily_prices_mean$Date))



```

```{r Cleaning empty values}
# Assuming your dataset is called Daily_prices_mean
column_names <- colnames(Daily_prices_mean)
columns_to_process <- setdiff(column_names, c("Day", "Date"))

Daily_prices_mean_we <- Daily_prices_mean %>%
  arrange(Date) %>%
  mutate(across(all_of(columns_to_process), 
                ~ ifelse(!Day %in% c("Saturday", "Sunday") & is.na(.), NA_real_, .),
                .names = "{.col}"))

# Use tidyr::fill to fill the weekend indicator
Daily_prices_mean_we <- Daily_prices_mean_we %>%
  tidyr::fill(everything(), .direction = "downup")

Daily_prices_mean_we <- Daily_prices_mean_we %>%
  mutate(across(all_of(columns_to_process),
                ~ ifelse(!Day %in% c("Saturday", "Sunday") & is.na(.), 
                         (lag(., default = first(na.omit(.))) + lead(., default = last(na.omit(.)))) / 2, .),
                .names = "{.col}_filled"))

Daily_prices_mean_we <- Daily_prices_mean_we %>% select(Date, Day, Cotton, Coffee, Sugar, Cocoa, Oil)
Daily_prices_mean_we <- Daily_prices_mean_we[-c(1:3), ]

```

```{r Delta price weekly}
Daily_prices_mean_we$Date <- as.Date(Daily_prices_mean_we$Date)
period_price_diff <- data.frame()

#Loop through each column in columns_to_process
for (col in columns_to_process) {
  # Initialize variables
  first_day_period <- NULL
  open_price <- NULL
  tuesday_count = 0
  
  for (i in 1:nrow(Daily_prices_mean_we)) {
    current_date <- Daily_prices_mean_we$Date[i]
    current_weekday <- Daily_prices_mean_we$Day[i]
    
    #If we're a tuesday and we already opened the week
    if ((tuesday_count == 1) & (current_weekday == "Tuesday")){
      tuesday_count=0
      #If it's not a Tuesday and we have a start date, calculate the price difference
      last_day_period <- current_date
      close_price <- Daily_prices_mean_we[[col]][i]
      price_diff <- round(close_price - open_price, 3)

      #Store the result in the data frame
      result <- data.frame(
        period = paste(first_day_period, last_day_period, sep = " - "),
        product = col,
        difference = price_diff
      )
      period_price_diff <- bind_rows(period_price_diff, result)
      
      #Next period
      first_day_period <- last_day_period
      open_price <- close_price
    }
    
    #If we're a tuesday and we didn't open the week
    if ((tuesday_count == 0) & (current_weekday == "Tuesday")) {
      # If it's a Tuesday, set the start of the period
      first_day_period <- current_date
      open_price <- Daily_prices_mean_we[[col]][i]
      tuesday_count = 1
      next
    }
    
  }
}

#Reshaping the dataframe
period_price_diff <- spread(period_price_diff, product, difference)

#Display the result
print(period_price_diff)



```



```{r creating COT dfs}
#Softs
COT_Cotton<- commodity_data_list[["Cotton"]]
COT_Cocoa<- commodity_data_list[["Cocoa"]]
COT_Coffee<- commodity_data_list[["Coffee"]]
COT_Sugar<- commodity_data_list[["Sugar"]]



#Other
# COT_Silver<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Silver") %>% as_tsibble(index= Date, regular=FALSE)
# COT_CrudeOil<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="CrudeOil") %>% as_tsibble(index= Date, regular=FALSE)
# COT_NagGas<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="NagGas") %>% as_tsibble(index= Date, regular=FALSE)
# COT_HeatOil<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="HeatOil") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Gasoline<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Gasoline") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Corn<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Corn") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Soybeans<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Soybeans") %>% as_tsibble(index= Date, regular=FALSE)
# COT_SoyOil<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="SoyOil") %>% as_tsibble(index= Date, regular=FALSE)
# COT_SoyMeal<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="SoyMeal") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Wheat<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Wheat") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Gold<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Gold") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Platinum<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Platinum") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Palladium<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Palladium") %>% as_tsibble(index= Date, regular=FALSE)
# COT_FedCattle<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="FedCattle") %>% as_tsibble(index= Date, regular=FALSE)
# COT_LiveCattle<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="LiveCattle") %>% as_tsibble(index= Date, regular=FALSE)
# COT_LeanHogs<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="LeanHogs") %>% as_tsibble(index= Date, regular=FALSE)
# COT_Copper<- read_excel("data/COT_Disaggreated_FuturesAndOptionsCombined.xlsx", sheet="Copper") %>% as_tsibble(index= Date, regular=FALSE)

```



```{r}

#Lagging the datasets


lager <- function(df) {
    # Lagging price set, we remove last row of t_1
    t_1 = df[-nrow(df), ]
    rownames(t_1) = NULL
    t_1$rows = 1:(nrow(df) - 1)
    # we remove first row of t
    t = df[-1, ]
    rownames(t) = NULL
    t$rows = 1:(nrow(df) - 1)

    # Merging the two sets
    t_lag = merge(t, t_1, by = "rows") %>% select(-rows)

    # Renaming features
    names(t_lag) <- gsub(".x", ".t", names(t_lag))
    names(t_lag) <- gsub(".y", ".t_1", names(t_lag))

    return(t_lag)
}


price_lag = lager(period_price_diff)
price_lag = price_lag[-c(1:141),]
rownames(price_lag) = NULL
price_lag$Date.t = substr(price_lag$period.t, 1, 10)
price_lag = price_lag %>% select(Date.t, everything())


COT_Sugar_lag = lager(COT_Sugar)
COT_Cocoa_lag = lager(COT_Cocoa)
COT_Coffee_lag = lager(COT_Coffee)
COT_Cotton_lag = lager(COT_Cotton)

sugar_price_cot <- merge(COT_Sugar_lag, price_lag, by = "Date.t")
cotton_price_cot <- merge(COT_Cotton_lag, price_lag, by = "Date.t")
cocoa_price_cot <- merge(COT_Cocoa_lag, price_lag, by = "Date.t")
coffee_price_cot <- merge(COT_Coffee_lag, price_lag, by = "Date.t")


write_csv(COT_Cocoa, "../ECOM-commodities/data/sugar_price_cot.csv")
write_csv(sugar_price_cot, "../ECOM-commodities/data/sugar_price_cot.csv")

# #Lagging price set
# price_t_1 = period_price_diff[-1043,]
# rownames(price_t_1) = NULL
# price_t_1$rows = 1:1042
# price_t = period_price_diff[-1,]
# rownames(price_t) = NULL
# price_t$rows = 1:1042
# 
# #merging the two sets
# price_lag = merge(price_t, price_t_1, by ="rows") %>% select(-rows)
# #renaming features
# names(price_lag) <- gsub(".x", ".t", names(price_lag))
# names(price_lag) <- gsub(".y", ".t_1", names(price_lag))

```




