---
title: "models cotton"
author: "Niccolò Cherubini"
date: "2023-12-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# COTTON

for each commo: open interest cotton \~ delta price cotton t + delta price cotton t_1 + open interest t_1 + other variables t_1

```{r}
#Data splitting for cotton
library(tidyverse)
library(caret)
library(randomForest)


# Splitting the dataset in 0.7 train - 0.3 test
set.seed(42) # for reproducibility

train_indices_cotton <- sample(1:nrow(cotton_price_cot), size = 0.7 * nrow(cotton_price_cot))
train_cotton <- cotton_price_cot[train_indices_cotton, ]
test_cotton <- cotton_price_cot[-train_indices_cotton, ]

# Selecting predictor variables
predictors_cotton <- names(cotton_price_cot)[grepl(".t_1", names(cotton_price_cot))]
predictors_cotton <- setdiff(predictors_cotton, c("Sugar.t_1", "Cocoa.t_1", "Coffee.t_1", "Sugar.t", "Cocoa.t", "Coffee.t"))


```

## AIC

```{r cotton LM AIC open interest}
#cotton LM

predictors_cotton_oi <- c(predictors_cotton, "Cotton.t")

#train data
train_cotton_oi <- train_cotton %>% select(all_of(c("Open_Interest.t", predictors_cotton_oi)))
train_cotton_oi <- train_cotton_oi %>% select_if(~is.numeric(.))

#test data
test_cotton_oi <- test_cotton %>% select(all_of(c("Open_Interest.t", predictors_cotton_oi)))
test_cotton_oi <- test_cotton_oi %>% select_if(~is.numeric(.))


# Linear model
cotton_lm_oi_aic <- lm(Open_Interest.t ~ ., data = train_cotton_oi)

# Stepwise model selection based on AIC
stepwise_cotton_oi <- step(cotton_lm_oi_aic, direction = "backward")

# Predict and evaluate the stepwise model
cotton_pred_oi_aic <- predict(stepwise_cotton_oi, test_cotton_oi)
mse_cotton_oi_aic <- mean((test_cotton_oi$Open_Interest.t - cotton_pred_oi_aic)^2)
r2_cotton_oi_aic <- summary(stepwise_cotton_oi)$r.squared
mae_cotton_oi_aic <- mean(abs(test_cotton_oi$Open_Interest.t - cotton_pred_oi_aic))

#Plotting predictions vs. test values
plot(cotton_pred_oi_aic ~ test_cotton_oi$Open_Interest.t, main="Predictions of LM AIC model for Open interest Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_pred_oi_aic~test_cotton_oi$Open_Interest.t), col="red")

# MSE, R-squared, and AIC
print(paste("MSE:", mse_cotton_oi_aic))
print(paste("R-squared:", r2_cotton_oi_aic))
print(summary(stepwise_cotton_oi))
cat("Mean Absolute Error (MAE):", mae_cotton_oi_aic, "\n")
#R-squared: 0.973180108288965
#AIC: 13281.2918272419

```

## RFE

```{r cotton LM RFE open interest}

# Set control parameters for RFE
control <- rfeControl(functions = rfFuncs, method = "cv", number = 10)

# Running RFE with random forest model
cotton_rfe_var_oi <- rfe(train_cotton_oi[, -which(names(train_cotton_oi) == "Open_Interest.t")], 
               train_cotton_oi$Open_Interest.t, 
               sizes = c(1:5),  # Number of features to include
               rfeControl = control)

# View results
print(cotton_rfe_var_oi)

cotton_oi_rfe = c("Total_Reportable_Shorts.t_1", "Open_Interest.t_1", "Total_Reportable_Longs.t_1", "Mon.t_1_Manager_Spreads.t", "Producer_Shorts.t_1")

train_cotton_oi_rfe <- train_cotton_oi %>% select(all_of(c("Open_Interest.t", "Cotton.t", cotton_oi_rfe)))
test_cotton_oi_rfe <- test_cotton_oi %>% select(all_of(c("Open_Interest.t", "Cotton.t", cotton_oi_rfe)))

# Linear model
cotton_lm_oi_rfe <- lm(Open_Interest.t ~ ., data = train_cotton_oi_rfe)


# Predict and evaluate the stepwise model
cotton_pred_oi_rfe <- predict(cotton_lm_oi_rfe, test_cotton_oi_rfe)
mse_cotton_oi_rfe <- mean((test_cotton_oi_rfe$Open_Interest.t - cotton_pred_oi_rfe)^2)
r2_cotton_oi_rfe <- summary(cotton_lm_oi_rfe)$r.squared
mae_cotton_oi_rfe <- mean(abs(test_cotton_oi_rfe$Open_Interest.t - cotton_pred_oi_rfe))


#Plotting predictions vs. test values
plot(cotton_pred_oi_rfe ~ test_cotton_oi_rfe$Open_Interest.t, main="Predictions of LM RFE model for Open interest Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_pred_oi_rfe~test_cotton_oi_rfe$Open_Interest.t), col="red")

# Print the MSE, R-squared, and AIC
print(paste("MSE:", mse_cotton_oi_rfe))
print(paste("R-squared:", r2_cotton_oi_rfe))
print(summary(cotton_lm_oi_rfe))
cat("Mean Absolute Error (MAE):", mae_cotton_oi_rfe, "\n")
#R-squared: 0.971484189620582
#AIC: 14517.2534706176

```

## LASSO

```{r cotton Open Interest LASSO Regression}

library(car)
library(readr)
library(dplyr)
library(tidyr)
library(caret)
library(glmnet)


# Calculate VIF
vif_cotton_oi <- lm(Open_Interest.t ~ ., data = train_cotton_oi)

# Calculate VIF
vif_cotton_oi_values <- vif(vif_cotton_oi)
vif_cotton_oi_table <- data.frame(Feature = names(vif_cotton_oi_values), VIF = vif_cotton_oi_values)

# Display the VIF table, sorted in descending order of VIF
vif_cotton_oi_table <- vif_cotton_oi_table %>% 
  arrange(desc(VIF)) %>% rename(`Feature Cotton` = Feature ) %>% 
  rownames_to_column() %>%  
  select(-rowname)      
print(vif_cotton_oi_table)
write_csv(vif_cotton_oi_table, "../ECOM-commodities/data/vif_cotton.csv")


# we define the target variable
target <- "Open_Interest.t"

# we define the features that will be used in the Lasso Regression. We remove variables that are highly correlated (cf. EDA correlation heatmaps)
features <- train_cotton_oi %>% 
  #select(- Open_Interest.t_1, - Total_Reportable_Shorts.t_1, -Total_Reportable_Longs.t_1, -Producer_Shorts.t_1, - `Other Reportable Spreads.t_1`) %>%
  select(-all_of(target)) %>% names()

# -Open_Interest.t_1,-Total_Reportable_Longs.t_1, -Total_Reportable_Shorts.t_1, -`Other Reportable Spreads.t_1`, - Mon.t_1_Manager_Spreads.t_1, -Producer_Shorts.t_1, -Producer_Longs.t_1

# Scale the features
preprocess_params_cotton_oi <- preProcess(train_cotton_oi[, features], method = c("center", "scale"))
cotton_train_scaled_oi <- predict(preprocess_params_cotton_oi, train_cotton_oi)
cotton_test_scaled_oi <- predict(preprocess_params_cotton_oi, test_cotton_oi)

# Train the Lasso model
set.seed(100) # for reproducibility
cotton_lasso_oi <- cv.glmnet(as.matrix(cotton_train_scaled_oi[, features]), cotton_train_scaled_oi[[target]], alpha = 1)

best_lambda <- cotton_lasso_oi$lambda.1se

# Make predictions and evaluate the model
cotton_lasso_pred_oi <- predict(cotton_lasso_oi, as.matrix(cotton_test_scaled_oi[, features]), s = "lambda.1se")
mse_cotton_lasso_oi <- mean((cotton_test_scaled_oi[[target]] - cotton_lasso_pred_oi)^2)
r2_cotton_lasso_oi <- cor(cotton_test_scaled_oi[[target]], as.vector(cotton_lasso_pred_oi))^2
mae_cotton_lasso_oi <- mean(abs(cotton_test_scaled_oi$Open_Interest.t - cotton_lasso_pred_oi))
cat("Mean Absolute Error (MAE):", mae_cotton_lasso_oi, "\n")

#Plotting predictions vs. test values
plot(cotton_lasso_pred_oi ~ cotton_test_scaled_oi$Open_Interest.t, main="Predictions of Lasso Open Interest Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_lasso_pred_oi~cotton_test_scaled_oi$Open_Interest.t), col="red")


# Extract coefficients at the best lambda value
cotton_lasso_coef_oi <- coef(cotton_lasso_oi, s = "lambda.1se")

# Convert the sparse matrix to a regular matrix, and then to a data frame
cotton_lasso_coef_df_oi <- as.data.frame(as.matrix(cotton_lasso_coef_oi))

# Add row names as a new column to the data frame
cotton_lasso_coef_df_oi$feature <- rownames(cotton_lasso_coef_df_oi)

#adjusted R-Squared
n_cotton_lasso_oi <- nrow(cotton_train_scaled_oi) # number of observations
p_cotton_lasso_oi <- sum(cotton_lasso_coef_df_oi$V1 != 0) - 1 # number of non-zero coefficients, excluding intercept
adj_r2_cotton_lasso_oi <- 1 - ( (1 - r2_cotton_lasso_oi) * (n_cotton_lasso_oi - 1) ) / (n_cotton_lasso_oi - p_cotton_lasso_oi - 1)

# Output the MSE, R-squared, and best lambda (alpha)
list(mse = mse_cotton_lasso_oi, r2 = r2_cotton_lasso_oi, adjusted_r2 = adj_r2_cotton_lasso_oi, Lambda = best_lambda)


# Filter out the intercept and the non-zero coefficients
cotton_lasso_selected_features_oi <- cotton_lasso_coef_df_oi[cotton_lasso_coef_df_oi$feature != "(Intercept)" & cotton_lasso_coef_df_oi$V1 != 0, ]

# Rename columns for clarity
names(cotton_lasso_selected_features_oi) <- c("Coefficient", "Feature")

# Print the selected features and their coefficients
print(cotton_lasso_selected_features_oi)

plot(cotton_lasso_oi)

# Calculate residuals
cotton_lasso_residuals_oi <- cotton_test_scaled_oi[[target]] - as.vector(cotton_lasso_pred_oi)

# Plot Residuals
plot(cotton_lasso_residuals_oi, ylab = "Residuals", xlab = "Predicted Values", main = "Residual Plot")
abline(h = 0, col = "red")

```

# MONEY MANAGERS

## SHORTS

### AIC

```{r}

predictors_cotton_MMS <- c(predictors_cotton, "Cotton.t")

#train data
train_cotton_MMS <- train_cotton %>% select(all_of(c("Mon.t_1_Manager_Shorts.t", predictors_cotton_MMS)))
train_cotton_MMS <- train_cotton_MMS %>% select_if(~is.numeric(.))

#test data
test_cotton_MMS <- test_cotton %>% select(all_of(c("Mon.t_1_Manager_Shorts.t", predictors_cotton_MMS)))
test_cotton_MMS <- test_cotton_MMS %>% select_if(~is.numeric(.))


# Linear model
cotton_lm_MMS_aic <- lm(Mon.t_1_Manager_Shorts.t ~ ., data = train_cotton_MMS)

# Stepwise model selection based on AIC
stepwise_cotton_MMS <- step(cotton_lm_MMS_aic, direction = "backward")

# Predict and evaluate the stepwise model
cotton_pred_MMS_aic <- predict(stepwise_cotton_MMS, test_cotton_MMS)
mse_cotton_MMS_aic <- mean((test_cotton_MMS$Mon.t_1_Manager_Shorts.t - cotton_pred_MMS_aic)^2)
r2_cotton_MMS_aic <- summary(stepwise_cotton_MMS)$r.squared
mae_cotton_MMS_aic <- mean(abs(test_cotton_MMS$Mon.t_1_Manager_Shorts.t - cotton_pred_MMS_aic))


#Plotting predictions vs. test values
plot(cotton_pred_MMS_aic ~ test_cotton_MMS$Mon.t_1_Manager_Shorts.t, main="Predictions of LM AIC model for MMS Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_pred_MMS_aic~test_cotton_MMS$Mon.t_1_Manager_Shorts.t), col="red")

# MSE, R-squared, and AIC
print(paste("MSE:", mse_cotton_MMS_aic))
print(paste("R-squared:", r2_cotton_MMS_aic))
print(summary(stepwise_cotton_MMS))
cat("Mean Absolute Error (MAE):", mae_cotton_MMS_aic, "\n")

```

### RFE

```{r}
# Set control parameters for RFE
control <- rfeControl(functions = rfFuncs, method = "cv", number = 10)

# Running RFE with random forest model
cotton_rfe_var_MMS <- rfe(train_cotton_MMS[, -which(names(train_cotton_MMS) == "Mon.t_1_Manager_Shorts.t")], 
               train_cotton_MMS$Mon.t_1_Manager_Shorts.t, 
               sizes = c(1:5),  # Number of features to include
               rfeControl = control)

# View results
print(cotton_rfe_var_MMS)

cotton_MMS_rfe = c("Mon.t_1_Manager_Shorts.t_1", "Non_Reportable_Shorts.t_1", "Producer_Shorts.t_1", "Swap_Dealer_Shorts.t_1", "Mon.t_1_Manager_Longs.t")

train_cotton_MMS_rfe <- train_cotton_MMS %>% select(all_of(c("Mon.t_1_Manager_Shorts.t", "Cotton.t", cotton_MMS_rfe)))
test_cotton_MMS_rfe <- test_cotton_MMS %>% select(all_of(c("Mon.t_1_Manager_Shorts.t", "Cotton.t", cotton_MMS_rfe)))

# Linear model
cotton_lm_MMS_rfe <- lm(Mon.t_1_Manager_Shorts.t ~ ., data = train_cotton_MMS_rfe)


# Predict and evaluate the stepwise model
cotton_pred_MMS_rfe <- predict(cotton_lm_MMS_rfe, test_cotton_MMS_rfe)
mse_cotton_MMS_rfe <- mean((test_cotton_MMS_rfe$Open_Interest.t - cotton_pred_MMS_rfe)^2)
r2_cotton_MMS_rfe <- summary(cotton_lm_MMS_rfe)$r.squared
mae_cotton_MMS_rfe <- mean(abs(test_cotton_MMS_rfe$Mon.t_1_Manager_Shorts.t- cotton_pred_MMS_rfe))

#Plotting predictions vs. test values
plot(cotton_pred_MMS_rfe ~ test_cotton_MMS_rfe$Mon.t_1_Manager_Shorts.t, main="Predictions of LM RFE model for MMS Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_pred_MMS_rfe~test_cotton_MMS_rfe$Mon.t_1_Manager_Shorts.t), col="red")


# Print the MSE, R-squared, and AIC
print(paste("MSE:", mse_cotton_MMS_rfe))
print(paste("R-squared:", r2_cotton_MMS_rfe))
print(summary(cotton_lm_MMS_rfe))
cat("Mean Absolute Error (MAE):", mae_cotton_MMS_rfe, "\n")


```

### LASSO

```{r cotton Money Managers Shorts LASSO Regression}
library(car)
library(readr)
library(dplyr)
library(tidyr)
library(caret)
library(glmnet)


# Calculate VIF
vif_cotton_MMS <- lm(Mon.t_1_Manager_Shorts.t ~ ., data = train_cotton_MMS)

# Calculate VIF
vif_cotton_MMS_values <- vif(vif_cotton_MMS)
vif_cotton_MMS_table <- data.frame(Feature = names(vif_cotton_MMS_values), VIF = vif_cotton_MMS_values)

# Display the VIF table, sorted in descending order of VIF
vif_cotton_MMS_table <- vif_cotton_MMS_table %>% 
  arrange(desc(VIF))
print(vif_cotton_MMS_table)


# we define the target variable
target <- "Mon.t_1_Manager_Shorts.t"

# we define the features that will be used in the Lasso Regression. We remove variables that are highly correlated
features <- train_cotton_MMS %>% 
  select(- Open_Interest.t_1, - Total_Reportable_Shorts.t_1, -Total_Reportable_Longs.t_1, -Producer_Shorts.t_1, - `Other Reportable Spreads.t_1`) %>%
  select(-all_of(target)) %>% names()


#-Open_Interest.t_1, -Total_Reportable_Longs.t_1, -Total_Reportable_Shorts.t_1, -`Other Reportable Spreads.t_1`, -Mon.t_1_Manager_Spreads.t_1, -Producer_Shorts.t_1, -Producer_Longs.t_1


# Scale the features
preprocess_params_cotton_MMS <- preProcess(train_cotton_MMS[, features], method = c("center", "scale"))
cotton_train_scaled_MMS <- predict(preprocess_params_cotton_MMS, train_cotton_MMS)
cotton_test_scaled_MMS <- predict(preprocess_params_cotton_MMS, test_cotton_MMS)

# Train the Lasso model
set.seed(100) # for reproducibility
cotton_lasso_MMS <- cv.glmnet(as.matrix(cotton_train_scaled_MMS[, features]), cotton_train_scaled_MMS[[target]], alpha = 1)

best_lambda <- cotton_lasso_MMS$lambda.1se

# Make predictions and evaluate the model
cotton_lasso_pred_MMS <- predict(cotton_lasso_MMS, as.matrix(cotton_test_scaled_MMS[, features]), s = "lambda.1se")
mse_cotton_lasso_MMS <- mean((cotton_test_scaled_MMS[[target]] - cotton_lasso_pred_MMS)^2)
r2_cotton_lasso_MMS <- cor(cotton_test_scaled_MMS[[target]], as.vector(cotton_lasso_pred_MMS))^2
mae_cotton_lasso_MMS <- mean(abs(cotton_test_scaled_MMS$Mon.t_1_Manager_Shorts.t - cotton_lasso_pred_MMS))

cat("Mean Absolute Error (MAE):", mae_cotton_lasso_MMS, "\n")

#Plotting predictions vs. test values
plot(cotton_lasso_pred_MMS ~ cotton_test_scaled_MMS$Mon.t_1_Manager_Shorts.t, main="Predictions of Lasso model for MMS Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_lasso_pred_MMS~cotton_test_scaled_MMS$Mon.t_1_Manager_Shorts.t), col="red")

# Extract coefficients at the best lambda value
cotton_lasso_coef_MMS <- coef(cotton_lasso_MMS, s = "lambda.1se")

# Convert the sparse matrix to a regular matrix, and then to a data frame
cotton_lasso_coef_df_MMS <- as.data.frame(as.matrix(cotton_lasso_coef_MMS))

# Add row names as a new column to the data frame
cotton_lasso_coef_df_MMS$feature <- rownames(cotton_lasso_coef_df_MMS)

#adjusted R-Squared
n_cotton_lasso_MMS <- nrow(cotton_train_scaled_MMS) # number of observations
p_cotton_lasso_MMS <- sum(cotton_lasso_coef_df_MMS$V1 != 0) - 1 # number of non-zero coefficients, excluding intercept
adj_r2_cotton_lasso_MMS <- 1 - ( (1 - r2_cotton_lasso_MMS) * (n_cotton_lasso_MMS - 1) ) / (n_cotton_lasso_MMS - p_cotton_lasso_MMS - 1)

# Output the MSE, R-squared, and best lambda (alpha)
list(mse = mse_cotton_lasso_MMS, r2 = r2_cotton_lasso_MMS, adjusted_r2 = adj_r2_cotton_lasso_MMS, Lambda = best_lambda)




# Filter out the intercept and the non-zero coefficients
cotton_lasso_selected_features_MMS <- cotton_lasso_coef_df_MMS[cotton_lasso_coef_df_MMS$feature != "(Intercept)" & cotton_lasso_coef_df_MMS$V1 != 0, ]

# Rename columns for clarity
names(cotton_lasso_selected_features_MMS) <- c("Coefficient", "Feature")

# Print the selected features and their coefficients
print(cotton_lasso_selected_features_MMS)

plot(cotton_lasso_MMS)

# Calculate residuals
cotton_lasso_residuals_MMS <- cotton_test_scaled_MMS[[target]] - as.vector(cotton_lasso_pred_MMS)

# Plot Residuals
plot(cotton_lasso_residuals_MMS, ylab = "Residuals", xlab = "Predicted Values", main = "Residual Plot")
abline(h = 0, col = "red")

# - Open_Interest.t_1, - Total_Reportable_Shorts.t_1, -Total_Reportable_Longs.t_1, -Producer_Shorts.t_1, - `Other Reportable Spreads.t_1`	

```

## Longs

### AIC
```{r}

predictors_cotton_MML <- c(predictors_cotton, "Cotton.t")

#train data
train_cotton_MML <- train_cotton %>% select(all_of(c("Mon.t_1_Manager_Longs.t", predictors_cotton_MML)))
train_cotton_MML <- train_cotton_MML %>% select_if(~is.numeric(.))

#test data
test_cotton_MML <- test_cotton %>% select(all_of(c("Mon.t_1_Manager_Longs.t", predictors_cotton_MML)))
test_cotton_MML <- test_cotton_MML %>% select_if(~is.numeric(.))


# Linear model
cotton_lm_MML_aic <- lm(Mon.t_1_Manager_Longs.t ~ ., data = train_cotton_MML)

# Stepwise model selection based on AIC
stepwise_cotton_MML <- step(cotton_lm_MML_aic, direction = "backward")

# Predict and evaluate the stepwise model
cotton_pred_MML_aic <- predict(stepwise_cotton_MML, test_cotton_MML)
mse_cotton_MML_aic <- mean((test_cotton_MML$Mon.t_1_Manager_Longs.t - cotton_pred_MML_aic)^2)
r2_cotton_MML_aic <- summary(stepwise_cotton_MML)$r.squared
mae_cotton_MML_aic <- mean(abs(test_cotton_MML$Mon.t_1_Manager_Longs.t - cotton_pred_MML_aic))

#Plotting predictions vs. test values
plot(cotton_pred_MML_aic ~ test_cotton_MML$Mon.t_1_Manager_Longs.t, main="Predictions of LM AIC model for MML Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_pred_MML_aic~test_cotton_MML$Mon.t_1_Manager_Longs.t), col="red")

# MSE, R-squared, and AIC
print(paste("MSE:", mse_cotton_MML_aic))
print(paste("R-squared:", r2_cotton_MML_aic))
print(summary(stepwise_cotton_MML))
cat("Mean Absolute Error (MAE):", mae_cotton_MML_aic, "\n")


```

### RFE
```{r}
# Set control parameters for RFE
control <- rfeControl(functions = rfFuncs, method = "cv", number = 10)

# Running RFE with random forest model
cotton_rfe_var_MML <- rfe(train_cotton_MML[, -which(names(train_cotton_MML) == "Mon.t_1_Manager_Longs.t")], 
               train_cotton_MML$Mon.t_1_Manager_Longs.t, 
               sizes = c(1:5),  # Number of features to include
               rfeControl = control)

# View results
print(cotton_rfe_var_MML)

cotton_MML_rfe = c("Mon.t_1_Manager_Longs.t_1", "Producer_Shorts.t_1", "Other_Reportable_Longs.t_1", "Cotton.t_1", "Mon.t_1_Manager_Shorts.t")

train_cotton_MML_rfe <- train_cotton_MML %>% select(all_of(c("Mon.t_1_Manager_Longs.t", "Cotton.t", cotton_MML_rfe)))
test_cotton_MML_rfe <- test_cotton_MML %>% select(all_of(c("Mon.t_1_Manager_Longs.t", "Cotton.t", cotton_MML_rfe)))

# Linear model
cotton_lm_MML_rfe <- lm(Mon.t_1_Manager_Longs.t ~ ., data = train_cotton_MML_rfe)


# Predict and evaluate the stepwise model
cotton_pred_MML_rfe <- predict(cotton_lm_MML_rfe, test_cotton_MML_rfe)
mse_cotton_MML_rfe <- mean((test_cotton_MML_rfe$Mon.t_1_Manager_Longs.t - cotton_pred_MML_rfe)^2)
r2_cotton_MML_rfe <- summary(cotton_lm_MML_rfe)$r.squared
mae_cotton_MML_rfe <- mean(abs(test_cotton_MML_rfe$Mon.t_1_Manager_Longs.t - cotton_pred_MML_rfe))

#Plotting predictions vs. test values
plot(cotton_pred_MML_rfe ~ test_cotton_MML_rfe$Mon.t_1_Manager_Longs.t, main="Predictions of LM RFE model for MML Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_pred_MML_rfe~test_cotton_MML_rfe$Mon.t_1_Manager_Longs.t), col="red")


# Print the MSE, R-squared, and AIC
print(paste("MSE:", mse_cotton_MML_rfe))
print(paste("R-squared:", r2_cotton_MML_rfe))
print(summary(cotton_lm_MML_rfe))
cat("Mean Absolute Error (MAE):", mae_cotton_MML_rfe, "\n")
```


### LASSO
```{r cotton Money Managers Shorts LASSO Regression}
library(car)
library(readr)
library(dplyr)
library(tidyr)
library(caret)
library(glmnet)


# Calculate VIF
vif_cotton_MML <- lm(Mon.t_1_Manager_Longs.t ~ ., data = train_cotton_MML)

# Calculate VIF
vif_cotton_MML_values <- vif(vif_cotton_MML)
vif_cotton_MML_table <- data.frame(Feature = names(vif_cotton_MML_values), VIF = vif_cotton_MML_values)

# Display the VIF table, sorted in descending order of VIF
vif_cotton_MML_table <- vif_cotton_MML_table %>% 
  arrange(desc(VIF))
print(vif_cotton_MML_table)


# we define the target variable
target <- "Mon.t_1_Manager_Longs.t"

# we define the features that will be used in the Lasso Regression. We remove variables that are highly correlated (cf. EDA correlation heatmaps)
features <- train_cotton_MML %>% 
  select(- Open_Interest.t_1, - Total_Reportable_Shorts.t_1, -Total_Reportable_Longs.t_1, -Producer_Shorts.t_1, - `Other Reportable Spreads.t_1`) %>%
  select(-all_of(target)) %>% names()


# Scale the features
preprocess_params_cotton_MML <- preProcess(train_cotton_MML[, features], method = c("center", "scale"))
cotton_train_scaled_MML <- predict(preprocess_params_cotton_MML, train_cotton_MML)
cotton_test_scaled_MML <- predict(preprocess_params_cotton_MML, test_cotton_MML)

# Train the Lasso model
set.seed(100) # for reproducibility
cotton_lasso_MML <- cv.glmnet(as.matrix(cotton_train_scaled_MML[, features]), cotton_train_scaled_MML[[target]], alpha = 1)

best_lambda <- cotton_lasso_MML$lambda.1se

# Make predictions and evaluate the model
cotton_lasso_pred_MML <- predict(cotton_lasso_MML, as.matrix(cotton_test_scaled_MML[, features]), s = "lambda.1se")
mse_cotton_lasso_MML <- mean((cotton_test_scaled_MML[[target]] - cotton_lasso_pred_MML)^2)
r2_cotton_lasso_MML <- cor(cotton_test_scaled_MML[[target]], as.vector(cotton_lasso_pred_MML))^2
mae_cotton_lasso_MML <- mean(abs(cotton_test_scaled_MML$Mon.t_1_Manager_Longs.t - cotton_lasso_pred_MML))

cat("Mean Absolute Error (MAE):", mae_cotton_lasso_MML, "\n")

#Plotting predictions vs. test values
plot(cotton_lasso_pred_MML ~cotton_test_scaled_MML$Mon.t_1_Manager_Longs.t, main="Predictions of Lasso model for MML Cotton vs. test values", xlab="Test values", ylab="Predicted values")
abline(lm(cotton_lasso_pred_MML~cotton_test_scaled_MML$Mon.t_1_Manager_Longs.t), col="red")

# Extract coefficients at the best lambda value
cotton_lasso_coef_MML <- coef(cotton_lasso_MML, s = "lambda.1se")

# Convert the sparse matrix to a regular matrix, and then to a data frame
cotton_lasso_coef_df_MML <- as.data.frame(as.matrix(cotton_lasso_coef_MML))

# Add row names as a new column to the data frame
cotton_lasso_coef_df_MML$feature <- rownames(cotton_lasso_coef_df_MML)

#adjusted R-Squared
n_cotton_lasso_MML <- nrow(cotton_train_scaled_MML) # number of observations
p_cotton_lasso_MML <- sum(cotton_lasso_coef_df_MML$V1 != 0) - 1 # number of non-zero coefficients, excluding intercept
adj_r2_cotton_lasso_MML <- 1 - ( (1 - r2_cotton_lasso_MML) * (n_cotton_lasso_MML - 1) ) / (n_cotton_lasso_MML - p_cotton_lasso_MML - 1)

# Output the MSE, R-squared, and best lambda (alpha)
list(mse = mse_cotton_lasso_MML, r2 = r2_cotton_lasso_MML, adjusted_r2 = adj_r2_cotton_lasso_MML, Lambda = best_lambda)


# Filter out the intercept and the non-zero coefficients
cotton_lasso_selected_features_MML <- cotton_lasso_coef_df_MML[cotton_lasso_coef_df_MML$feature != "(Intercept)" & cotton_lasso_coef_df_MML$V1 != 0, ]

# Rename columns for clarity
names(cotton_lasso_selected_features_MML) <- c("Coefficient", "Feature")

# Print the selected features and their coefficients
print(cotton_lasso_selected_features_MML)

plot(cotton_lasso_MML)

# Calculate residuals
cotton_lasso_residuals_MML <- cotton_test_scaled_MML[[target]] - as.vector(cotton_lasso_pred_MML)

# Plot Residuals
plot(cotton_lasso_residuals_MML, ylab = "Residuals", xlab = "Predicted Values", main = "Residual Plot")
abline(h = 0, col = "red")

```

```{r}

saveRDS(stepwise_cotton_oi, "models_pred/stepwise_cotton_oi.rds")
saveRDS(stepwise_cotton_MMS, "models_pred/stepwise_cotton_MMS.rds")
saveRDS(stepwise_cotton_MML, "models_pred/stepwise_cotton_MML.rds")

```